apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: webrtc-back
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: asia.gcr.io/synergy-249605/pvms-websocket
      # local build - macbook m1 (arm64)
    custom:
      buildCommand: docker buildx build --platform linux/amd64 -t asia.gcr.io/synergy-249605/pvms-websocket . --push
      dependencies:
        paths:
        - .
    # docker:
    #   dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - Kubernetes-Manifests/Deployment.yaml
    - Kubernetes-Manifests/Service.yaml
